spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdbs;MODE=MySQL;NON_KEYWORDS=user
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.example.springcloudaws.domain.user: debug
#    io.awspring.cloud: debug